### ISSUE TITLE
JavaScript integration

### ISSUE THREAD

**Issue by VladanStojanovic** [zhaber/grules#5]
Hi.

I read your (great) thesis yesterday and spent the rest of the day trying out the code and analyzing the source. The thesis describes client-side (JavaScript) integration to such a detail that I thought it is already implemented in the framework, but nothing of the sort could I find in the repository. This is not something you got around to do, correct?

Would be great if there was a framework in Java addressing this, seems peculiar to me that there isn't, but I guess people don't like their validations DRY.  Had a proprietary integration between .NET FluentValidation and client-side validation based on much the same principles you describe in the thesis and I'm thinking of picking up grules and adding the integration part myself. Is that the way to go, no Chapter 11 implemented somewhere else (e.g. another GitHub repository)?

Thanks.

**Comment by zhaber** [comment]
Hey Vladan,

Thanks for your interest in Grules. There is no integration with JavaScript at the moment but it's possible to implement in accordance with the thesis. The only caveat is custom lambdas, which a developer should map to js functions manually; another option is try to [translate](http://grooscript.org) groovy code to javascript automatically. GitHub [documentation](https://github.com/zhaber/grules/wiki) describes the current implementation of grules. As you might found, the main translation logic lives in https://github.com/zhaber/grules/tree/master/grules/src/main/groovy/org/grules/ast Let me know if you need any help.

**Comment by VladanStojanovic** [comment]
Thank you for the swift response.

I'll be probably analyzing this in more detail in the days to come and start implementing the JavaScript part if I don't find a viable ready-made alternative elsewhere.

Will be checking out the Grooscript too, thanks for the tip!
