### ISSUE TITLE
Passing custom functions via environment in Java

### ISSUE THREAD

**Issue by rsteppac** [zhaber/grules#6]
I am trying to get the passing of custom functions to work using Java. 

I have a class with static methods as described [here](https://github.com/zhaber/grules/wiki/Rules-and-functions-scripts).

One of the static methods is

```
public static boolean isHP(final User user) {
    return user instanceof HealthProfessional;
}
```

I tried passing in an instance of the class or the class itself via the environment map like so:

```
// ...
Map<String,Object> environment = new HashMap<>();
environment.put("customValidators", CustomValidators.class);
// ...
RulesScriptResult result = grules.applyRules(rule, params, environment);
// ...
```

The rule script:
```
package ch.vivates.rules.groovy

user customValidators.isHP
```

The closest I have come is an error `groovy.lang.MissingPropertyException: No such property: isHP for class: ch.vivates.rules.functions.CustomValidators`. Which is at least the correct class. With other variants the engine tries to resolve “isHP” on the script class itself.
The Grules unit test `EnvironmentTest` uses a single function definition in the environment map and references it directly by name. However, I don’t see how to do this using Java?

Any help on this would be appreciated

**Comment by zhaber** [comment]
A standard way is to use `import` in the grules script:

    import static CustomValidators.*

    user isHP   

To pass a Java method as an environment variable from a groovy script you will need to use `&`, for example:

    environment.put("isHP", CustomValidators.&isHP)

Then in the grules script:

    user isHP   

For java it's a little bit more verbose:
 
    environment.put("isHP", new MethodClosure(CustomValidators.class, "isHP"));

If you want to pass a java class as Functions:

    environment.put("customValidators", CustomValidators.class);

calls must to be converted to MethodClosures in the script itself: 

    user {customValidators.&isHP(it)}

**Comment by zhaber** [comment]
I also added support for direct a call method closure in the last commit.

https://github.com/zhaber/grules/wiki/MethodClosure

**Comment by rsteppac** [comment]
Thanks! For now I went with the solution to add the static imports for my validator methods via an ImportCustomizer.
